CREATE VIEW PROJ_EMPS AS
SELECT Pname, Lname, Fname, Hours
FROM EMPLOYEE, PROJECT, WORKS_ON
WHERE Ssn = Essn AND Pno = Pnumber ORDER BY Pname, Lname, Fname ASC; 

SELECT * FROM PROJ_EMPS;

CREATE VIEW PROJ_SUMMARY
AS SELECT Pname, COUNT(E.Ssn) AS NO_OF_EMPLOYEE, SUM(Hours) AS TOTAL_HOURS
FROM EMPLOYEE E, PROJECT, WORKS_ON
WHERE Ssn = Essn AND Pno = Pnumber GROUP BY Pname ORDER BY Pname DESC;

SELECT * FROM PROJ_SUMMARY;