CREATE DATABASE IF NOT EXISTS companydb DEFAULT CHARACTER SET latin1;
USE companydb;

DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE (
Fname VARCHAR(50) NOT NULL,
Minit VARCHAR(50), 
Lname VARCHAR(50) NOT NULL, 
Ssn CHAR(9) NOT NULL, 
Bdate VARCHAR(20),
Address VARCHAR(100),
Sex CHAR,
Salary DECIMAL(10,2),
Super_ssn CHAR(9),
Dno INT NOT NULL,
PRIMARY KEY (Ssn)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE DEPARTMENT (
Dname VARCHAR(50) NOT NULL,
Dnumber INT NOT NULL,
Mgr_ssn CHAR(9) NOT NULL,
Mgr_start_date VARCHAR(20),
PRIMARY KEY (Dnumber),
UNIQUE(Dname),
FOREIGN KEY (Mgr_ssn) REFERENCES EMPLOYEE(Ssn)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS DEPT_LOCATIONS;
CREATE TABLE DEPT_LOCATIONS (
Dnumber INT NOT NULL,
Dlocation VARCHAR(100) NOT NULL,
PRIMARY KEY (Dnumber, Dlocation),
FOREIGN KEY (Dnumber) REFERENCES DEPARTMENT(Dnumber)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS PROJECT;
CREATE TABLE PROJECT (
Pname VARCHAR(50) NOT NULL,
Pnumber INT NOT NULL,
Plocation VARCHAR(100),
Dnum INT NOT NULL,
PRIMARY KEY (Pnumber),
UNIQUE(Pname),
FOREIGN KEY (Dnum) REFERENCES DEPARTMENT(Dnumber)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS WORKS_ON;
CREATE TABLE WORKS_ON (
Essn CHAR(9) NOT NULL,
Pno INT NOT NULL,
Hours DECIMAL(3,1) NOT NULL,
PRIMARY KEY (Essn, Pno),
FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn),
FOREIGN KEY (Pno) REFERENCES PROJECT(Pnumber)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

SET foreign_key_checks = 0;

LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\EMPLOYEE-1.txt' INTO TABLE EMPLOYEE FIELDS TERMINATED BY ', ' ENCLOSED BY "'" LINES TERMINATED BY '\r\n';
LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\DEPARTMENT-1.txt' INTO TABLE DEPARTMENT FIELDS TERMINATED BY ', ' ENCLOSED BY "'" LINES TERMINATED BY '\r\n';
LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\DEPT_LOCATIONS-1.txt' INTO TABLE DEPT_LOCATIONS FIELDS TERMINATED BY ', ' ENCLOSED BY "'" LINES TERMINATED BY '\r\n';
LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\PROJECT-1.txt' INTO TABLE PROJECT FIELDS TERMINATED BY ', ' ENCLOSED BY "'" LINES TERMINATED BY '\r\n';
LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\WORKS_ON-1.txt' INTO TABLE WORKS_ON FIELDS TERMINATED BY ', ' ENCLOSED BY "'" LINES TERMINATED BY '\r\n';

SET foreign_key_checks = 1;

SELECT * FROM companydb.employee;
SELECT * FROM companydb.department;
SELECT * FROM companydb.dept_locations;
SELECT * FROM companydb.project;
SELECT * FROM companydb.works_on;


